# Oral History as Data (OHD) - a Lib-STATIC Tool
# https://github.com/uidaholib/oral-history-as-data


##########
# URL settings 
#
# url is your gh-pages base, following the pattern: username.github.io
url: https://ubc-library-rbsc.github.io
# baseurl is your github repository's name prefixed with a /
baseurl: /gillis-2021_ohd
# repository is the github repository's full url
repository: https://github.com/ubc-library-rbsc/gillis-2021_ohd


##########
# Site settings
#
# title of site appears in banner
title: I Know We'll Meet Again - Transcripts
# tagline appears in banner
tagline: Correspondence and the forced dispersal of Japanese Canadians
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: "This digital exhibition on Japanese Canadian forced dispersal and internment features materials from the Joan Gillis fonds, housed at the University of British Columbia Library's Rare Books and Special Collections."
# Organization branding
organization-name:
organization-link:
organization-logo-banner: 
organization-logo-nav: 


####### Leave the Below As Is ########

# Jekyll collections settings
collections:
  transcripts:
    output: true
    permalink: /:collection/:name
  howto:
    output: true
    permalink: /:collection/:name
# defaults
defaults:
  - scope:
      type: transcripts
    values:
      layout: transcript
  - scope:
      type: howto
    values:
      layout: howto

# Build settings
markdown: kramdown

